### ISSUE TITLE
PM Review: Events

### ISSUE THREAD

**Issue by lambyy** [lambyy/eventation#16]

**Comment by LochandQuay** [comment]
@lambyy 

Console Errors: 
- When trying to add an image to a new event (event form): `Uncaught TypeError: Cannot read property 'openUploadWidget' of undefined`
  - Can't create image because of this. :(
- When clicking "Browse Events" from new event form: `GET https://eventation.herokuapp.com/api/events/browse 404 (Not Found) ["Event does not exist"]`

Other: 
- You'll need better seed data (that isn't faker/lorem ipsum)

Styling looks good!

**Comment by lambyy** [comment]
@LochandQuay 

Console Errors: 

- I was able to fix the error on adding an image to event form
- I changed the Browse Event Page to temporarily show the event index. I will change this later to browse by categories when I implement categories

Other:

- Seed data is no longer lorem ipsum

**Comment by LochandQuay** [comment]
@lambyy 

So close! There's a `500 Internal Server Error` when I submit a new event. These are usually database issues (missing migrations, etc.)

**Comment by lambyy** [comment]
@LochandQuay 

I finished adding a form for tickets on the event form page and it seems to work now.
